name: lab-no-supervisado
channels:
  - conda-forge
dependencies:
  - python=3.11
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - fastapi
      - "uvicorn[standard]"
      - pydantic
      - joblib
      - httpx